// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/maxio-advanced-billing-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.MaxioAdvancedBillingSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.MaxioAdvancedBillingSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.MaxioAdvancedBillingSDK, name string) (sdk.MaxioAdvancedBillingEntity, error) {
	switch strings.ToLower(name) {
	case "account_balance":
		return client.AccountBalance(nil), nil
	case "allocation":
		return client.Allocation(nil), nil
	case "batch_job":
		return client.BatchJob(nil), nil
	case "billing_portal":
		return client.BillingPortal(nil), nil
	case "component":
		return client.Component(nil), nil
	case "component_feature":
		return client.ComponentFeature(nil), nil
	case "component_price_point":
		return client.ComponentPricePoint(nil), nil
	case "component_price_point_currency_overage":
		return client.ComponentPricePointCurrencyOverage(nil), nil
	case "coupon":
		return client.Coupon(nil), nil
	case "coupon_currency":
		return client.CouponCurrency(nil), nil
	case "coupon_subcode":
		return client.CouponSubcode(nil), nil
	case "coupon_usage":
		return client.CouponUsage(nil), nil
	case "custom_field":
		return client.CustomField(nil), nil
	case "customer":
		return client.Customer(nil), nil
	case "delayed_cancel":
		return client.DelayedCancel(nil), nil
	case "endpoint":
		return client.Endpoint(nil), nil
	case "entitlement":
		return client.Entitlement(nil), nil
	case "event":
		return client.Event(nil), nil
	case "events_based_billing_segment":
		return client.EventsBasedBillingSegment(nil), nil
	case "feature":
		return client.Feature(nil), nil
	case "feature_catalog_item":
		return client.FeatureCatalogItem(nil), nil
	case "feature_template":
		return client.FeatureTemplate(nil), nil
	case "insight":
		return client.Insight(nil), nil
	case "invoice":
		return client.Invoice(nil), nil
	case "list_proforma_invoice":
		return client.ListProformaInvoice(nil), nil
	case "list_sale_rep_item":
		return client.ListSaleRepItem(nil), nil
	case "list_segment":
		return client.ListSegment(nil), nil
	case "offer":
		return client.Offer(nil), nil
	case "one_time_token":
		return client.OneTimeToken(nil), nil
	case "payment_profile":
		return client.PaymentProfile(nil), nil
	case "prepayment":
		return client.Prepayment(nil), nil
	case "product":
		return client.Product(nil), nil
	case "product_family":
		return client.ProductFamily(nil), nil
	case "product_feature":
		return client.ProductFeature(nil), nil
	case "product_price_point":
		return client.ProductPricePoint(nil), nil
	case "proforma_invoice":
		return client.ProformaInvoice(nil), nil
	case "reason_code":
		return client.ReasonCode(nil), nil
	case "referral_code":
		return client.ReferralCode(nil), nil
	case "sale_rep_setting":
		return client.SaleRepSetting(nil), nil
	case "sales_commission":
		return client.SalesCommission(nil), nil
	case "segment":
		return client.Segment(nil), nil
	case "signup_proforma_preview":
		return client.SignupProformaPreview(nil), nil
	case "site":
		return client.Site(nil), nil
	case "subscription":
		return client.Subscription(nil), nil
	case "subscription_component":
		return client.SubscriptionComponent(nil), nil
	case "subscription_group":
		return client.SubscriptionGroup(nil), nil
	case "subscription_group_invoice_account":
		return client.SubscriptionGroupInvoiceAccount(nil), nil
	case "subscription_group_signup":
		return client.SubscriptionGroupSignup(nil), nil
	case "subscription_group_status":
		return client.SubscriptionGroupStatus(nil), nil
	case "subscription_invoice_account":
		return client.SubscriptionInvoiceAccount(nil), nil
	case "subscription_mrr":
		return client.SubscriptionMrr(nil), nil
	case "subscription_note":
		return client.SubscriptionNote(nil), nil
	case "subscription_product":
		return client.SubscriptionProduct(nil), nil
	case "subscription_renewal":
		return client.SubscriptionRenewal(nil), nil
	case "subscription_status":
		return client.SubscriptionStatus(nil), nil
	case "usage":
		return client.Usage(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
