<?php
declare(strict_types=1);

// MaxioAdvancedBilling SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MaxioAdvancedBillingUtility::setRegistrar(function (MaxioAdvancedBillingUtility $u): void {
    $u->clean = [MaxioAdvancedBillingClean::class, 'call'];
    $u->done = [MaxioAdvancedBillingDone::class, 'call'];
    $u->make_error = [MaxioAdvancedBillingMakeError::class, 'call'];
    $u->feature_add = [MaxioAdvancedBillingFeatureAdd::class, 'call'];
    $u->feature_hook = [MaxioAdvancedBillingFeatureHook::class, 'call'];
    $u->feature_init = [MaxioAdvancedBillingFeatureInit::class, 'call'];
    $u->fetcher = [MaxioAdvancedBillingFetcher::class, 'call'];
    $u->make_fetch_def = [MaxioAdvancedBillingMakeFetchDef::class, 'call'];
    $u->make_context = [MaxioAdvancedBillingMakeContext::class, 'call'];
    $u->make_options = [MaxioAdvancedBillingMakeOptions::class, 'call'];
    $u->make_request = [MaxioAdvancedBillingMakeRequest::class, 'call'];
    $u->make_response = [MaxioAdvancedBillingMakeResponse::class, 'call'];
    $u->make_result = [MaxioAdvancedBillingMakeResult::class, 'call'];
    $u->make_point = [MaxioAdvancedBillingMakePoint::class, 'call'];
    $u->make_spec = [MaxioAdvancedBillingMakeSpec::class, 'call'];
    $u->make_url = [MaxioAdvancedBillingMakeUrl::class, 'call'];
    $u->param = [MaxioAdvancedBillingParam::class, 'call'];
    $u->prepare_auth = [MaxioAdvancedBillingPrepareAuth::class, 'call'];
    $u->prepare_body = [MaxioAdvancedBillingPrepareBody::class, 'call'];
    $u->prepare_headers = [MaxioAdvancedBillingPrepareHeaders::class, 'call'];
    $u->prepare_method = [MaxioAdvancedBillingPrepareMethod::class, 'call'];
    $u->prepare_params = [MaxioAdvancedBillingPrepareParams::class, 'call'];
    $u->prepare_path = [MaxioAdvancedBillingPreparePath::class, 'call'];
    $u->prepare_query = [MaxioAdvancedBillingPrepareQuery::class, 'call'];
    $u->graphql_body = [MaxioAdvancedBillingGraphql::class, 'body'];
    $u->graphql_errors = [MaxioAdvancedBillingGraphql::class, 'errors'];
    $u->result_basic = [MaxioAdvancedBillingResultBasic::class, 'call'];
    $u->result_body = [MaxioAdvancedBillingResultBody::class, 'call'];
    $u->result_headers = [MaxioAdvancedBillingResultHeaders::class, 'call'];
    $u->transform_request = [MaxioAdvancedBillingTransformRequest::class, 'call'];
    $u->transform_response = [MaxioAdvancedBillingTransformResponse::class, 'call'];
});
